### ISSUE TITLE
Can't Update Firmware Via ESPHome Dashboard

### ISSUE THREAD

**Issue by sbailey151** [KaufHA/kauf-rgb-switch#14]
Here's the error I get when I try to update the firmware on my switch via the ESPHome dashboard.

```
INFO ESPHome 2023.9.3
INFO Reading configuration /config/esphome/den-accent-light-switch.yaml...
ERROR Unexpected exception while reading configuration:
Traceback (most recent call last):
  File "/usr/local/bin/esphome", line 33, in <module>
    sys.exit(load_entry_point('esphome', 'console_scripts', 'esphome')())
  File "/esphome/esphome/__main__.py", line 1036, in main
    return run_esphome(sys.argv)
  File "/esphome/esphome/__main__.py", line 1014, in run_esphome
    config = read_config(dict(args.substitution) if args.substitution else {})
  File "/esphome/esphome/config.py", line 986, in read_config
    res = load_config(command_line_substitutions)
  File "/esphome/esphome/config.py", line 840, in load_config
    return _load_config(command_line_substitutions)
  File "/esphome/esphome/config.py", line 828, in _load_config
    result = validate_config(config, command_line_substitutions)
  File "/esphome/esphome/config.py", line 690, in validate_config
    substitutions.do_substitution_pass(config, command_line_substitutions)
  File "/esphome/esphome/components/substitutions/__init__.py", line 143, in do_substitution_pass
    config.move_to_end(CONF_SUBSTITUTIONS, False)
AttributeError: 'dict' object has no attribute 'move_to_end'
```

**Comment by bkaufx** [comment]
Working fine for me.  What does your yaml look like?

**Comment by bkaufx** [comment]
This seems like an issue with your ESPHome install, like something is out of wack.  Maybe try uninstalling and reinstalling or something.  Back up all your yaml configs.

**Comment by sbailey151** [comment]
Thanks.  I removed the switch from ESP home and reset it up, but now I'm getting a different error when trying to "Install":

`======================== [SUCCESS] Took 154.16 seconds ========================
INFO Successfully compiled program.
INFO Resolving IP address of den-accent-light-switch.local
INFO  -> 192.168.86.52
ERROR Connecting to den-accent-light-switch.local:3232 failed: [Errno 111] Connection refused`
